FROM ubuntu
RUN echo "Hello-Ravi" > /tmp/tesfile

#######################################
FROM ubuntu
WORKDIR /tmp
RUN echo "Hello_Ravi"> /tmp/testfile
ENV name=Ravi
COPY testfile /tmp/
ADD test.tar.gz /tmp/
##########################################