---
- name: This playbook install apache2
  hosts: all
  become: true
  tasks:
  - name: Installing apache2
    apt:
      name: apache2
      state: present
    notify: starting service
  handlers:
  - name: starting service
    service:
      name: apache2
      state: started
...