---
- name: This playbook is for install Tomcat
  become: true
  hosts: all
  tasks:
  - name: Update the package
    apt:
      upgrade: yes
      update_cache: yes

  - name: Create the tomcat user
    user:
      name: tomcat
  
  - name: Create the tomcat group
    group:
      name: tomcat

  - name: Install Java
    apt:
      name: default-jdk
      state: present

  - name: Create the directory
    file:
      path: /opt/tomcat10
      owner: tomcat
      group: tomcat
      mode: 755
      recurse: yes

  - name: Download and uarchive tomcat
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.tar.gz
      dest: /opt/tomcat10
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership of tomcat directory
    file:
      path: /opt/tomcat10
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Creating a service file
    copy:
      content: |-
        [Unit]
        Description=Apache Tomcat 
        Requires=network.target
        After=network.target
        
        [Service]
        Type=forking
        
        # Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        Environment="CATALINA_PID=/opt/tomcat10/temp/tomcat.pid"
        Environment="CATALINA_HOME=/opt/tomcat10"
        Environment="CATALINA_BASE=/opt/tomcat10"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        
        ExecStart=/opt/tomcat10/bin/startup.sh
        ExecStop=/opt/tomcat10/bin/shutdown.sh
        
        User=tomcat
        Group=tomcat
        UMask=0007
        Restart=always
        
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service
    
  - name: Reload the SystemD to re-read configurations
    become: yes
    systemd:
      daemon-reload: yes
  - name: Enable the tomcat service and start
    become: yes
    systemd:
      name: tomcat
      enabled: yes
      state: started
  - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
    tags: test
    uri:
      url: http://localhost:8080
    register: result
    until: "result.status == 200"
    retries: 5
    delay: 10    
... 