---
# tasks file for setup-apache-role
- name: Installing httpd package
  yum:
    name: httpd
    state: latest
  when: ansible_os_family == "RedHat"
- name: Installing apache2 package
  apt:
    name: apache2
    state: latest
  when: ansible_os_family == "Debian"
- name: Deploy webpage
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: 0666
    remote_src: true
...

